<img src="./julia_logo.png" align="center" width="400"/>

System information (for reproducibility)

In [133]:
versioninfo()

Julia Version 1.12.5
Commit 5fe89b8ddc1 (2026-02-09 16:05 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 8 default, 1 interactive, 8 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = code


Load packages:

In [134]:
using Pkg
Pkg.activate(pwd())
Pkg.instantiate()
Pkg.status()

  Activating project at `~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro`


Status `~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/Project.toml`
  [6e4b80f9] BenchmarkTools v1.6.3
  [31c24e10] Distributions v0.25.123
  [6f49c342] RCall v0.14.12
  [37e2e46d] LinearAlgebra v1.12.0
  [9abbd945] Profile v1.11.0
  [2f01184e] SparseArrays v1.12.0


In [135]:
using BenchmarkTools, Distributions, RCall
using LinearAlgebra, Profile, SparseArrays

## What's Julia?

> Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments

* History:
  - Project started in 2009. First public release in 2012 
  - Creators: Jeff Bezanson, Alan Edelman, Stefan Karpinski, Viral Shah
  - First major release v1.0 was released on Aug 8, 2018
  - Current stable release v1.11.4 (as of Apr 1, 2025)

* Aim to solve the notorious **two language problem**: Prototype code goes into high-level languages like R/Python, production code goes into low-level language like C/C++. 

    Julia aims to:  
    
> Walks like Python. Runs like C.

<img src="./julia_vs_otherlang.png" align="center" width="600"/>

See <https://julialang.org/benchmarks/> for the details of benchmark.

* Write high-level, abstract code that closely resembles mathematical formulas
    - yet produces fast, low-level machine code that has traditionally only been generated by static languages.

* Julia is more than just "Fast R" or "Fast Matlab"
    - Performance comes from features that work well together.  
    - You can't just take the magic dust that makes Julia fast and sprinkle it on [language of choice]

## Learning resources

1. The (free) online course [Introduction to Julia](https://juliaacademy.com/p/intro-to-julia), by Jane Herriman. 

2. Cheat sheet: [The Fast Track to Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/).  

3. Browse the Julia [documentation](https://docs.julialang.org/en).  

4. For Matlab users, read [Noteworthy Differences From Matlab](https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Noteworthy-differences-from-MATLAB-1).  

    For R users, read [Noteworthy Differences From R](https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Noteworthy-differences-from-R-1).  

    For Python users, read [Noteworthy Differences From Python](https://docs.julialang.org/en/v1/manual/noteworthy-differences/?highlight=matlab#Noteworthy-differences-from-Python-1).  

5. The [Learning page](http://julialang.org/learning/) on Julia's website has pointers to many other learning resources.  

## Julia REPL (Read-Evaluation-Print-Loop)

The `Julia` REPL, or `Julia` shell, has at least five modes.

1. **Default mode** is the Julian prompt `julia>`. Type backspace in other modes to enter default mode.    

2. **Help mode** `help?>`. Type `?` to enter help mode. `?search_term` does a fuzzy search for `search_term`.  

3. **Shell mode** `shell>`. Type `;` to enter shell mode.  

4. **Package mode** `(@v1.11) pkg>`. Type `]` to enter package mode for managing Julia packages (install, uninstall, update, ...).

5. **Search mode** `(reverse-i-search)`. Press `ctrl+R` to enter search model. 

6. With `RCall.jl` package installed, we can enter the **R mode** by typing `$` (shift+4) at Julia REPL.

Some survival commands in Julia REPL:  

1. `exit()` or `Ctrl+D`: exit Julia.

2. `Ctrl+C`: interrupt execution.

3. `Ctrl+L`: clear screen.

0. Append `;` (semi-colon) to suppress displaying output from a command. Same as Matlab.

0. `include("filename.jl")` to source a Julia code file.

## Seek help

* Online help from REPL: `?function_name`.

* Google.

* Julia documentation: <https://docs.julialang.org/en/>.

* Look up source code: `@edit sin(π)`.

* Discourse: <https://discourse.julialang.org>.

* Friends.

## Which IDE?

* Many choices: Positron, VS Code, Vim, ...

* For dynamic document, e.g., homework, I recommend [JupyterLab](http://jupyterlab.readthedocs.io/en/stable/) or VS Code (with Jupyter extension) or Positron. 

* For extensive Julia coding, myself has been happily using [VS Code](https://code.visualstudio.com) with extensions `Julia` and `VS Code Jupyter Notebook Previewer` installed. 

## Julia package system

* Each Julia package is a Git repository. Each Julia package name ends with `.jl`. E.g., `Distributions.jl` package lives at <https://github.com/JuliaStats/Distributions.jl>.   
Google search with `PackageName.jl` usually leads to the package on github.com. 

* The package ecosystem is rapidly maturing; a complete list of **registered** packages (which are required to have a certain level of testing and documentation) is at [http://pkg.julialang.org/](http://pkg.julialang.org/).

* For example, the package called `Distributions.jl` is added with
```julia
# in Pkg mode
(@v1.12) pkg> add Distributions
```
and "removed" (although not completely deleted) with
```julia
# in Pkg mode
(@v1.12) pkg> rm Distributions
```
* The package manager provides a dependency solver that determines which packages are actually required to be installed.

* **Non-registered** packages are added by cloning the relevant Git repository. E.g.,
```julia
# in Pkg mode
(@v1.12) pkg> add https://github.com/OpenMendel/SnpArrays.jl
```

* A package needs only be added once, at which point it is downloaded into your local `.julia/packages` directory in your home directory. 

In [136]:
readdir(Sys.islinux() ? ENV["JULIA_PATH"] * "/pkg/packages" : ENV["HOME"] * "/.julia/packages")

870-element Vector{String}:
 "ADTypes"
 "AMD"
 "ANSIColoredPrinters"
 "ASL_jll"
 "AbstractAlgebra"
 "AbstractFFTs"
 "AbstractLattices"
 "AbstractTrees"
 "Accessors"
 "AccurateArithmetic"
 ⋮
 "libvorbis_jll"
 "libwebp_jll"
 "micromamba_jll"
 "mtdev_jll"
 "oneTBB_jll"
 "pixi_jll"
 "x264_jll"
 "x265_jll"
 "xkbcommon_jll"

* Directory of a specific package can be queried by `pathof()`:

In [137]:
pathof(Distributions)

"/Users/huazhou/.julia/packages/Distributions/xMnxM/src/Distributions.jl"

* If you start having problems with packages that seem to be unsolvable, you may try just deleting your .julia directory and reinstalling all your packages. 

* Periodically, one should run `update` in Pkg mode, which checks for, downloads and installs updated versions of all the packages you currently have installed.

* `status` lists the status of all installed packages.

* Using functions in package.
```julia
using Distributions
```
This pulls all of the *exported* functions in the module into your local namespace, as you can check using the `whos()` command. An alternative is
```julia
import Distributions
```
Now, the functions from the Distributions package are available only using 
```julia
Distributions.<FUNNAME>
```
All functions, not only exported functions, are always available like this.

## Calling R from Julia

* The [`RCall.jl`](https://github.com/JuliaInterop/RCall.jl) package allows us to embed R code inside of Julia.

* There are also `PyCall.jl`, `MATLAB.jl`, `JavaCall.jl`, `CxxWrap.jl` packages for interfacing with other languages.

In [138]:
# x is in Julia workspace
x = randn(1000)

# $ is the interpolation operator
R"""
hist($x, main = "I'm plotting a Julia vector")
""";

In [139]:
R"""
library(ggplot2)

qplot($x)
"""

RObject{S4Sxp}


┌ Warning: RCall.jl: `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
└ @ RCall /Users/huazhou/.julia/packages/RCall/FKyW5/src/io.jl:166


In [140]:
x = R"""
rnorm(10)
"""

RObject{RealSxp}
 [1]  0.7352400 -1.7517739  0.1324266 -0.5412487 -0.7634409 -0.7183970
 [7]  0.5775719 -0.7142623  0.4175035 -0.4385484


In [141]:
# collect R variable into Julia workspace
y = collect(x)

10-element Vector{Float64}:
  0.7352400475280704
 -1.7517738819296178
  0.13242658602558952
 -0.5412486959989523
 -0.7634408700370287
 -0.718396955045106
  0.5775718505392854
 -0.7142622758368488
  0.4175035260175291
 -0.4385483859456067

* Access Julia variables in R REPL mode:
```julia
julia> x = rand(5) # Julia variable
R> y <- $x
```

* Pass Julia expression in R REPL mode:
```julia
R> y <- $(rand(5))
```

* Put Julia variable into R environment:
```julia
julia> @rput x
R> x
```

* Get R variable into Julia environment:
```julia
R> r <- 2
Julia> @rget r
```

* If you want to call Julia within R, check out the [`JuliaCall`](https://non-contradiction.github.io/JuliaCall//index.html) package.

## Some basic Julia code

In [142]:
# an integer, same as int in R
y = 1

1

In [143]:
# query type of a Julia object
typeof(y)

Int64

In [144]:
# a Float64 number, same as double in R
y = 1.0

1.0

In [145]:
typeof(y) 

Float64

In [146]:
# Greek letters:  `\pi<tab>`
π

π = 3.1415926535897...

In [147]:
typeof(π)

Irrational{:π}

In [148]:
# Greek letters:  `\theta<tab>`
θ = y + π

4.141592653589793

In [149]:
# emoji! `\:kissing_cat:<tab>`
😽 = 5.0
😽 + 1

6.0

In [150]:
# `\alpha<tab>\hat<tab>`
α̂ = π

π = 3.1415926535897...

For a list of unicode symbols that can be tab-completed, see <https://docs.julialang.org/en/v1/manual/unicode-input/>. Or in the help mode, type `?` followed by the unicode symbol you want to input.

In [151]:
# vector of Float64 0s
x = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [152]:
# vector Int64 0s
x = zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [153]:
# matrix of Float64 0s
x = zeros(5, 3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [154]:
# matrix of Float64 1s
x = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [155]:
# define array without initialization
x = Matrix{Float64}(undef, 5, 3)

5×3 Matrix{Float64}:
 1.9188e-319   4.0e-323   4.94e-322
 2.74703e-314  1.6e-322   4.94e-321
 2.74703e-314  1.5e-323   1.235e-321
 1.5e-323      5.0e-324   1.6e-322
 2.0e-323      3.01e-314  2.40382e-314

In [156]:
# fill a matrix by 0s
fill!(x, 0)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [157]:
# initialize an array to be constant 2.5
fill(2.5, (5, 3))

5×3 Matrix{Float64}:
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5

In [158]:
# rational number
a = 3//5

3//5

In [159]:
typeof(a)

Rational{Int64}

In [160]:
b = 3//7

3//7

In [161]:
a + b

36//35

In [162]:
# uniform [0, 1) random numbers
x = rand(5, 3)

5×3 Matrix{Float64}:
 0.221066  0.269709   0.999898
 0.837369  0.734658   0.761776
 0.379295  0.348791   0.202427
 0.548195  0.947714   0.173401
 0.72821   0.0356481  0.470909

In [163]:
# uniform random numbers (in single precision)
x = rand(Float16, 5, 3)

5×3 Matrix{Float16}:
 0.356   0.9277  0.3037
 0.8057  0.1587  0.7334
 0.5713  0.4873  0.3896
 0.875   0.253   0.5513
 0.911   0.2964  0.2915

In [164]:
# random numbers from {1,...,5}
x = rand(1:5, 5, 3)

5×3 Matrix{Int64}:
 4  1  4
 5  1  2
 1  5  3
 2  2  4
 3  2  5

In [165]:
# standard normal random numbers
x = randn(5, 3)

5×3 Matrix{Float64}:
  1.25878    0.353313   1.19879
 -1.06628   -0.382405   0.00677371
  0.759393   1.41359    0.987596
  2.52169    0.364274   1.6534
 -0.691151   2.06407   -0.0802506

In [166]:
# range
1:10

1:10

In [167]:
typeof(1:10)

UnitRange{Int64}

In [168]:
1:2:10

1:2:9

In [169]:
typeof(1:2:10)

StepRange{Int64, Int64}

In [170]:
# integers 1-10
x = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [171]:
# or equivalently
[1:10...]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [172]:
# Float64 numbers 1-10
x = collect(1.0:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [173]:
# convert to a specific type
convert(Vector{Float64}, 1:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [174]:
# syntactically same as above
Float64.(1:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

## Matrices and vectors

### Dimensions

In [175]:
x = randn(5, 3)

5×3 Matrix{Float64}:
 -1.74026   -2.20092    -1.20329
  0.273892   1.23902    -0.614638
  0.614875  -0.430023    0.499991
  0.291039   0.0826336  -0.300265
  0.781258   1.28138     0.934036

In [176]:
size(x)

(5, 3)

In [177]:
size(x, 1) # nrow() in R

5

In [178]:
size(x, 2) # ncol() in R

3

In [179]:
# total number of elements
length(x)

15

### Indexing

In [180]:
# 5 × 5 matrix of random Normal(0, 1)
x = randn(5, 5)

5×5 Matrix{Float64}:
 -0.624908    0.507281   0.579177  0.746938    1.06985
 -1.00696    -0.993942  -2.25949   0.6096      1.6568
 -0.349952   -0.951403  -0.160082  0.759202    0.24515
 -0.0805672  -0.52992   -0.739701  0.0754985   0.455776
  0.304362    0.240862   0.506253  2.35056    -0.130875

In [181]:
# first column
x[:, 1]

5-element Vector{Float64}:
 -0.6249077560505156
 -1.006957863148905
 -0.3499517593664053
 -0.08056718498329925
  0.3043620078537337

In [182]:
# first row
x[1, :]

5-element Vector{Float64}:
 -0.6249077560505156
  0.5072811260130184
  0.5791766846507604
  0.7469375445260727
  1.0698521976789046

In [183]:
# sub-array
x[1:2, 2:3]

2×2 Matrix{Float64}:
  0.507281   0.579177
 -0.993942  -2.25949

In [184]:
# getting a subset of a matrix creates a copy, but you can also create "views"
z = view(x, 1:2, 2:3)

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
  0.507281   0.579177
 -0.993942  -2.25949

In [185]:
# same as
@views z = x[1:2, 2:3]

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
  0.507281   0.579177
 -0.993942  -2.25949

In [186]:
# change in z (view) changes x as well
z[2, 2] = 0.0
x

5×5 Matrix{Float64}:
 -0.624908    0.507281   0.579177  0.746938    1.06985
 -1.00696    -0.993942   0.0       0.6096      1.6568
 -0.349952   -0.951403  -0.160082  0.759202    0.24515
 -0.0805672  -0.52992   -0.739701  0.0754985   0.455776
  0.304362    0.240862   0.506253  2.35056    -0.130875

In [187]:
# y points to same data as x
y = x

5×5 Matrix{Float64}:
 -0.624908    0.507281   0.579177  0.746938    1.06985
 -1.00696    -0.993942   0.0       0.6096      1.6568
 -0.349952   -0.951403  -0.160082  0.759202    0.24515
 -0.0805672  -0.52992   -0.739701  0.0754985   0.455776
  0.304362    0.240862   0.506253  2.35056    -0.130875

In [188]:
# x and y point to same data
pointer(x), pointer(y)

(Ptr{Float64}(0x0000000156939de0), Ptr{Float64}(0x0000000156939de0))

In [189]:
# changing y also changes x
y[:, 1] .= 0
x

5×5 Matrix{Float64}:
 0.0   0.507281   0.579177  0.746938    1.06985
 0.0  -0.993942   0.0       0.6096      1.6568
 0.0  -0.951403  -0.160082  0.759202    0.24515
 0.0  -0.52992   -0.739701  0.0754985   0.455776
 0.0   0.240862   0.506253  2.35056    -0.130875

In [190]:
# create a new copy of data
z = copy(x)

5×5 Matrix{Float64}:
 0.0   0.507281   0.579177  0.746938    1.06985
 0.0  -0.993942   0.0       0.6096      1.6568
 0.0  -0.951403  -0.160082  0.759202    0.24515
 0.0  -0.52992   -0.739701  0.0754985   0.455776
 0.0   0.240862   0.506253  2.35056    -0.130875

In [191]:
pointer(x), pointer(z)

(Ptr{Float64}(0x0000000156939de0), Ptr{Float64}(0x000000015693abe0))

### Concatenate matrices

In [192]:
# 3-by-1 vector
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [193]:
# 1-by-3 array
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [194]:
# multiple assignment by tuple
x, y, z = randn(5, 3), randn(5, 2), randn(3, 5)

([0.3502026954381819 -0.5289902412082321 -1.2567336815408456; 0.7923593830513104 -1.140278302969866 -1.0965103045630669; … ; 1.105875842751859 0.8794444649463151 -0.2700967196474576; -1.6416386265986596 0.5755649013305568 0.03277017098738286], [-0.3035495013152559 0.7299187667303698; -0.13892883758643143 1.2765882873958725; … ; 0.81420157255065 1.465918565943446; 1.331172530790042 -0.8756528112467492], [-0.2991249243383505 -0.7506114590808598 … 0.44497526703139584 -0.6859993978513388; 0.5832560391690074 0.36858394454434645 … -0.9451821729747875 -2.2536786520784036; 0.2669290346560834 0.5359995664727822 … -0.4360769312138808 0.44053791950128435])

In [195]:
[x y] # 5-by-5 matrix

5×5 Matrix{Float64}:
  0.350203  -0.52899   -1.25673    -0.30355    0.729919
  0.792359  -1.14028   -1.09651    -0.138929   1.27659
 -0.459877  -0.568182  -0.429985    0.725034   0.745222
  1.10588    0.879444  -0.270097    0.814202   1.46592
 -1.64164    0.575565   0.0327702   1.33117   -0.875653

In [196]:
[x y; z] # 8-by-5 matrix

8×5 Matrix{Float64}:
  0.350203  -0.52899   -1.25673    -0.30355    0.729919
  0.792359  -1.14028   -1.09651    -0.138929   1.27659
 -0.459877  -0.568182  -0.429985    0.725034   0.745222
  1.10588    0.879444  -0.270097    0.814202   1.46592
 -1.64164    0.575565   0.0327702   1.33117   -0.875653
 -0.299125  -0.750611   0.140601    0.444975  -0.685999
  0.583256   0.368584   1.51119    -0.945182  -2.25368
  0.266929   0.536     -1.21802    -0.436077   0.440538

### Dot operation (broadcasting)

Dot operation in Julia is elementwise operation, similar to Matlab.

In [197]:
x = randn(5, 3)

5×3 Matrix{Float64}:
 -0.783117  -0.509395  -0.137451
 -0.210181  -0.827468  -0.154559
  0.493686  -1.92371    1.43026
  0.915177   0.693011   1.335
 -1.55439    1.51393    0.0761057

In [198]:
y = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [199]:
x .* y # same x * y in R

5×3 Matrix{Float64}:
 -0.783117  -0.509395  -0.137451
 -0.210181  -0.827468  -0.154559
  0.493686  -1.92371    1.43026
  0.915177   0.693011   1.335
 -1.55439    1.51393    0.0761057

In [200]:
x .^ (-2)

5×3 Matrix{Float64}:
  1.6306    3.85381    52.9304
 22.6368    1.46049    41.8611
  4.10297   0.270221    0.488844
  1.19396   2.08219     0.561094
  0.413888  0.436306  172.649

In [201]:
sin.(x)

5×3 Matrix{Float64}:
 -0.705492  -0.487649  -0.137018
 -0.208637  -0.73622   -0.153944
  0.473875  -0.938368   0.990141
  0.792671   0.638856   0.972329
 -0.999865   0.998383   0.0760323

### Basic linear algebra

In [202]:
x = randn(5)

5-element Vector{Float64}:
  0.27938102525869685
 -0.06778690810197267
  0.16902612780379914
  0.030793524794558425
 -0.3986115856350001

In [203]:
# vector L2 norm
norm(x)

0.5206323956849922

In [204]:
# same as
sqrt(sum(abs2, x))

0.5206323956849922

In [205]:
y = randn(5) # another vector
# dot product
dot(x, y) # x' * y

-0.03240749389230025

In [206]:
# same as
x'y

-0.03240749389230025

In [207]:
x, y = randn(5, 3), randn(3, 2)
# matrix multiplication, same as %*% in R
x * y

5×2 Matrix{Float64}:
  3.48105    1.69082
 -0.602308   0.885984
 -2.70484   -1.92865
 -2.60164   -1.32217
  0.123317   0.779754

In [208]:
x = randn(3, 3)

3×3 Matrix{Float64}:
 -1.34188  -0.24743     0.926284
 -1.05759   0.212499   -0.50941
  1.1165    0.0404575   3.11988

In [209]:
# conjugate transpose
x'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -1.34188   -1.05759   1.1165
 -0.24743    0.212499  0.0404575
  0.926284  -0.50941   3.11988

In [210]:
b = rand(3)
x'b # same as x' * b

3-element Vector{Float64}:
 -0.48182558704081946
 -0.17619498857687313
  3.4668161880893766

In [211]:
# trace
tr(x)

1.990505809107782

In [212]:
det(x)

-1.8523642028192482

In [213]:
rank(x)

3

### Sparse matrices

In [214]:
# 10-by-10 sparse matrix with sparsity 0.1
X = sprandn(10, 10, .1)

10×10 SparseMatrixCSC{Float64, Int64} with 12 stored entries:
   ⋅         ⋅         ⋅    ⋅        …   ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅   -0.626017
   ⋅        0.909744   ⋅    ⋅           1.28839   0.82996    ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅   0.235919      ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅        …   ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅        1.21012    ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅       -0.586429   ⋅     ⋅ 
 -0.469626  1.59982    ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 

In [215]:
# dump() in Julia is like str() in R
dump(X)

SparseMatrixCSC{Float64, Int64}
  m: Int64 10
  n: Int64 10
  colptr: Array{Int64}((11,)) [1, 2, 4, 4, 5, 5, 8, 9, 12, 12, 13]
  rowval: Array{Int64}((12,)) [9, 3, 9, 5, 5, 7, 8, 3, 3, 7, 8, 2]
  nzval: Array{Float64}((12,)) [-0.4696259081416942, 0.9097437806538611, 1.599816568984336, 0.23591931267246338, -2.3251967613349906, -0.14263743080392377, -0.9897100887084765, 1.2883878290070865, 0.8299596076661482, 1.2101192848804392, -0.5864293929656963, -0.6260172067546129]


In [216]:
# convert to dense matrix; be cautious when dealing with big data
Xfull = convert(Matrix{Float64}, X)

10×10 Matrix{Float64}:
  0.0       0.0       0.0  0.0       …  0.0       0.0       0.0   0.0
  0.0       0.0       0.0  0.0          0.0       0.0       0.0  -0.626017
  0.0       0.909744  0.0  0.0          1.28839   0.82996   0.0   0.0
  0.0       0.0       0.0  0.0          0.0       0.0       0.0   0.0
  0.0       0.0       0.0  0.235919     0.0       0.0       0.0   0.0
  0.0       0.0       0.0  0.0       …  0.0       0.0       0.0   0.0
  0.0       0.0       0.0  0.0          0.0       1.21012   0.0   0.0
  0.0       0.0       0.0  0.0          0.0      -0.586429  0.0   0.0
 -0.469626  1.59982   0.0  0.0          0.0       0.0       0.0   0.0
  0.0       0.0       0.0  0.0          0.0       0.0       0.0   0.0

In [217]:
# convert a dense matrix to sparse matrix
sparse(Xfull)

10×10 SparseMatrixCSC{Float64, Int64} with 12 stored entries:
   ⋅         ⋅         ⋅    ⋅        …   ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅   -0.626017
   ⋅        0.909744   ⋅    ⋅           1.28839   0.82996    ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅   0.235919      ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅        …   ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅        1.21012    ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅       -0.586429   ⋅     ⋅ 
 -0.469626  1.59982    ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 
   ⋅         ⋅         ⋅    ⋅            ⋅         ⋅         ⋅     ⋅ 

In [218]:
# syntax for sparse linear algebra is same as dense linear algebra
β = ones(10)
X * β

10-element Vector{Float64}:
  0.0
 -0.6260172067546129
  3.0280912173270957
  0.0
 -2.089277448662527
  0.0
  1.0674818540765154
 -1.576139481674173
  1.1301906608426417
  0.0

In [219]:
# many functions apply to sparse matrices as well
sum(X)

0.9343295951549401

## Control flow and loops

* if-elseif-else-end

```julia
if condition1
    # do something
elseif condition2
    # do something
else
    # do something
end
```

* `for` loop

```julia
for i in 1:10
    println(i)
end
```

* Nested `for` loop:

```julia
for i in 1:10
    for j in 1:5
        println(i * j)
    end
end
```
Same as

```julia
for i in 1:10, j in 1:5
    println(i * j)
end
```

* Exit loop:

```julia
for i in 1:10
    # do something
    if condition1
        break # skip remaining loop
    end
end
```

* Exit iteration:  

```julia
for i in 1:10
    # do something
    if condition1
        continue # skip to next iteration
    end
    # do something
end
```

## Functions 

* In Julia, all arguments to functions are **passed by reference**, in contrast to R and Matlab.

* Function names ending with `!` indicates that function mutates at least one argument, typically the first.
```julia
sort!(x) # vs sort(x)
```

* Function definition

```julia
function func(req1, req2; key1=dflt1, key2=dflt2)
    # do stuff
    return out1, out2, out3
end
```
**Required arguments** are separated with a comma and use the positional notation.  
**Optional arguments** need a default value in the signature.  
**Semicolon** is not required in function call.  
**return** statement is optional.  
Multiple outputs can be returned as a **tuple**, e.g., `return out1, out2, out3`.  

* Anonymous functions, e.g., `x -> x^2`, is commonly used in collection function or list comprehensions.
```julia
map(x -> x^2, y) # square each element in x
```

* Functions can be nested:

```julia
function outerfunction()
    # do some outer stuff
    function innerfunction()
        # do inner stuff
        # can access prior outer definitions
    end
    # do more outer stuff
end
```

* Scalar functions can be vectorized using the Dot syntax:

In [220]:
# defined for scalar
function myfunc(x)
    return sin(x^2)
end

x = randn(5, 3)
myfunc.(x)

5×3 Matrix{Float64}:
 0.108558    0.669796   0.898987
 0.0348798   0.711472   0.760366
 0.939013    0.721256   0.0619582
 0.00243967  0.0350587  0.106257
 0.955324    0.63404    0.0274041

* **Collection function** (think this as the series of `apply` functions in R).

    Apply a function to each element of a collection:

```julia
map(f, coll) # or
map(coll) do elem
    # do stuff with elem
    # must contain return
end
```

In [221]:
map(x -> sin(x^2), x)

5×3 Matrix{Float64}:
 0.108558    0.669796   0.898987
 0.0348798   0.711472   0.760366
 0.939013    0.721256   0.0619582
 0.00243967  0.0350587  0.106257
 0.955324    0.63404    0.0274041

In [222]:
map(x) do elem
    elem = elem^2
    return sin(elem)
end

5×3 Matrix{Float64}:
 0.108558    0.669796   0.898987
 0.0348798   0.711472   0.760366
 0.939013    0.721256   0.0619582
 0.00243967  0.0350587  0.106257
 0.955324    0.63404    0.0274041

In [223]:
# Mapreduce
mapreduce(x -> sin(x^2), +, x)

6.666809839995158

In [224]:
# same as
sum(x -> sin(x^2), x)

6.666809839995158

* List **comprehension**

In [225]:
[sin(2i + j) for i in 1:5, j in 1:3] # similar to Python

5×3 Matrix{Float64}:
  0.14112   -0.756802  -0.958924
 -0.958924  -0.279415   0.656987
  0.656987   0.989358   0.412118
  0.412118  -0.544021  -0.99999
 -0.99999   -0.536573   0.420167

## Type system

* Every variable in Julia has a type.

* When thinking about types, think about sets.

* Everything is a subtype of the abstract type `Any`.

* An abstract type defines a set of types
    - Consider types in Julia that are a `Number`:

<img src="tree.png" width="800" align="center"/>

* We can explore type hierarchy with `typeof()`, `supertype()`, and `subtypes()`.

In [226]:
# 1.0: double precision, 1: 64-bit integer
typeof(1.0), typeof(1)

(Float64, Int64)

In [227]:
supertype(Float64)

AbstractFloat

In [228]:
subtypes(AbstractFloat)

5-element Vector{Any}:
 BigFloat
 Core.BFloat16
 Float16
 Float32
 Float64

In [229]:
# Is Float64 a subtype of AbstractFloat?
Float64 <: AbstractFloat

true

In [230]:
# On 64bit machine, Int == Int64
Int == Int64

true

In [231]:
# convert to Float64
convert(Float64, 1)

1.0

In [232]:
# same as casting
Float64(1)

1.0

In [233]:
# Float32 vector
x = randn(Float32, 5)

5-element Vector{Float32}:
 -0.057060886
  0.14128895
 -0.20184669
  0.6943516
  0.7109638

In [234]:
# convert to Float64
convert(Vector{Float64}, x)

5-element Vector{Float64}:
 -0.057060886174440384
  0.14128895103931427
 -0.20184668898582458
  0.6943516135215759
  0.710963785648346

In [235]:
# same as broadcasting (dot operatation)
Float64.(x)

5-element Vector{Float64}:
 -0.057060886174440384
  0.14128895103931427
 -0.20184668898582458
  0.6943516135215759
  0.710963785648346

In [236]:
# convert Float64 to Int64
convert(Int, 1.0)

1

In [237]:
convert(Int, 1.5) # should use round(1.5)

InexactError: InexactError: Int64(1.5)

In [238]:
round(Int, 1.5)

2

## Multiple dispatch

* Multiple dispatch lies in the core of Julia design. It allows built-in and user-defined functions to be overloaded for different combinations of argument types.

* Let's consider a simple "doubling" function:

In [239]:
g(x) = x + x

g (generic function with 3 methods)

In [240]:
g(1.5)

3.0

This definition is too broad, since some things, e.g., strings, can't be added 

In [241]:
g("hello world")

MethodError: MethodError: no method matching +(::String, ::String)
The function `+` exists, but no method is defined for this combination of argument types.
String concatenation is performed with * (See also: https://docs.julialang.org/en/v1/manual/strings/#man-concatenation).

Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:642
  +(!Matched::Pkg.Resolve.FieldValue, !Matched::Pkg.Resolve.FieldValue)
   @ Pkg ~/.julia/juliaup/julia-1.12.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Pkg/src/Resolve/fieldvalues.jl:45
  +(!Matched::Bool, !Matched::Complex{Bool})
   @ Base complex.jl:308
  ...


* This definition is correct but too restrictive, since any `Number` can be added.

In [242]:
g(x::Float64) = x + x

g (generic function with 3 methods)

* This definition will automatically work on the entire type tree above!

In [243]:
g(x::Number) = x + x

g (generic function with 3 methods)

This is a lot nicer than 
```julia
function g(x)
    if isa(x, Number)
        return x + x
    else
        throw(ArgumentError("x should be a number"))
    end
end
```

* `methods(func)` function display all methods defined for `func`.

In [244]:
methods(g)

# 3 methods for generic function "g" from Main:
 [1] g(x::Float64)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1
 [2] g(x::Number)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1
 [3] g(x)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y236sZmlsZQ==.jl:1

* When calling a function with multiple definitions, Julia will search from the narrowest signature to the broadest signature.

* `@which func(x)` marco tells which method is being used for argument signature `x`.

In [245]:
# an Int64 input
@which g(1)

g(x::Number)
     @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1

In [246]:
# a Vector{Float64} input
@which g(randn(5))

g(x)
     @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y236sZmlsZQ==.jl:1

## Just-in-time compilation (JIT)

Following figures are taken from Arch D. Robinson's slides [Introduction to Writing High Performance Julia](https://www.youtube.com/watch?v=szE4txAD8mk).


| <img src="./julia_toolchain.png" alt="Julia toolchain" style="width: 400px;"/> | <img src="./julia_introspect.png" alt="Julia toolchain" style="width: 500px;"/> |
|----------------------------------|------------------------------------|
|||

* `Julia`'s efficiency results from its capability to infer the types of **all** variables within a function and then call LLVM compiler to generate optimized machine code at run-time. 

Consider the `g` (doubling) function defined earlier. This function will work on **any** type which has a method for `+`.

In [247]:
g(2), g(2.0)

(4, 4.0)

**Step 1**: Parse Julia code into [abstract syntax tree (AST)](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

In [248]:
@code_lowered g(2)

CodeInfo(
1 ─ %1 = Main.:+
│   %2 =   dynamic (%1)(x, x)
└──      return %2
)

**Step 2**: Type inference according to input type.

In [249]:
# type inference for integer input
@code_warntype g(2)

MethodInstance for g(::Int64)
  from g(x::Number) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1
Arguments
  #self#::Core.Const(Main.g)
  x::Int64
Body::Int64
1 ─ %1 = Main.:+::Core.Const(+)
│   %2 = (%1)(x, x)::Int64
└──      return %2



In [250]:
# type inference for Float64 input
@code_warntype g(2.0)

MethodInstance for g(::Float64)
  from g(x::Float64) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1
Arguments
  #self#::Core.Const(Main.g)
  x::Float64
Body::Float64
1 ─ %1 = Main.:+::Core.Const(+)
│   %2 = (%1)(x, x)::Float64
└──      return %2



**Step 3**: Compile into **LLVM bitcode** (equivalent of R bytecode generated by the `compiler` package).

In [251]:
# LLVM bitcode for integer input
@code_llvm g(2)

; Function Signature: g(Int64)
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1 within `g`
define i64 @julia_g_36259(i64 signext %"x::Int64") #0 {
top:
; ┌ @ int.jl:87 within `+`
   %0 = shl i64 %"x::Int64", 1
   ret i64 %0
; └
}


In [252]:
# LLVM bitcode for Float64 input
@code_llvm g(2.0)

; Function Signature: g(Float64)
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1 within `g`
define double @julia_g_36261(double %"x::Float64") #0 {
top:
; ┌ @ float.jl:495 within `+`
   %0 = fadd double %"x::Float64", %"x::Float64"
   ret double %0
; └
}


We didn't provide a type annotation. But different LLVM bitcodes were generated depending on the argument type!

In R or Python, `g(2)` and `g(2.0)` would use the same code for both.

In Julia, `g(2)` and `g(2.0)` dispatches to optimized code for `Int64` and `Float64`, respectively.

For integer input `x`, LLVM compiler is smart enough to know `x + x` is simply shifting `x` by 1 bit, which is faster than addition.
 
* **Step 4**: Lowest level is the **assembly code**, which is machine dependent.

In [253]:
# Assembly code for integer input
@code_native g(2)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_g_36264                  ; -- Begin function julia_g_36264
	.p2align	2
_julia_g_36264:                         ; @julia_g_36264
; Function Signature: g(Int64)
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1 within `g`
; %bb.0:                                ; %top
	;DEBUG_VALUE: g:x <- $x0
	;DEBUG_VALUE: g:x <- $x0
; │┌ @ int.jl:87 within `+`
	lsl	x0, x0, #1
	ret
; └└
                                        ; -- End function
.subsections_via_symbols


In [254]:
# Assembly code for Float64 input
@code_native g(2.0)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_g_36266                  ; -- Begin function julia_g_36266
	.p2align	2
_julia_g_36266:                         ; @julia_g_36266
; Function Signature: g(Float64)
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1 within `g`
; %bb.0:                                ; %top
	;DEBUG_VALUE: g:x <- $d0
	;DEBUG_VALUE: g:x <- $d0
; │┌ @ float.jl:495 within `+`
	fadd	d0, d0, d0
	ret
; └└
                                        ; -- End function
	.section	__DATA,__const
	.p2align	3, 0x0                          ; @"+Core.Float64#36268"
"l_+Core.Float64#36268":
	.quad	"l_+Core.Float64#36268.jit"

.set "l_+Core.Float64#36268.jit", 4910797568
.subsections_via_symbols


## Profiling Julia code

Julia has several built-in tools for profiling. The `@time` marco outputs run time and heap allocation. Note the first call of a function incurs (substantial) compilation time.

In [255]:
# a function defined earlier
function tally(x::Array)
    s = zero(eltype(x))
    for v in x
        s += v
    end
    s
end

using Random
Random.seed!(257)
a = rand(20_000_000)
@time tally(a) # first run: include compile time

  0.022711 seconds (4.70 k allocations: 217.406 KiB, 19.05% compilation time)


1.000097950627383e7

In [256]:
@time tally(a)

  0.017774 seconds (1 allocation: 16 bytes)


1.000097950627383e7

For more robust benchmarking, the [BenchmarkTools.jl](https://github.com/JuliaCI/BenchmarkTools.jl) package is highly recommended.

In [257]:
@benchmark tally($a)

BenchmarkTools.Trial: 299 samples with 1 evaluation per sample.
 Range (min … max):  16.349 ms …  18.111 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.739 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   16.752 ms ± 184.096 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                          █▅  ▁                                 
  ▂▃▄▃▃▃▃▂▂▂▃▃▃▃▃▄▄▃▄▄▆▆█▇█████▆▇▅█▃▃▃▃▄▁▃▃▄▃▃▃▂▁▁▂▂▁▂▁▁▃▁▂▁▁▂ ▃
  16.3 ms         Histogram: frequency by time         17.3 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.

The `Profile` module gives line by line profile results.

In [258]:
Profile.clear()
@profile tally(a)
Profile.print(format=:flat)

 Count  Overhead File                    Line Function
 =====  ======== ====                    ==== ========
    12         0 @Base/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/base/Base.jl:306\Base.jl]8;;\           306 include(mod::Module, _path::Strin…
    12         0 @Base/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/base/array.jl:901\array.jl]8;;\          901 iterate
    12         0 @Base/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/base/boot.jl:489\boot.jl]8;;\           489 eval(m::Module, e::Any)
    12         0 @Base/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/base/client.jl:550\client.jl]8;;\         550 _start()
    12         0 @Base/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/bas

One can use [`ProfileView`](https://github.com/timholy/ProfileView.jl) package for better visualization of profile data:

```julia
using ProfileView

ProfileView.view()
```

In [259]:
# check type stability
@code_warntype tally(a)

MethodInstance for tally(::Vector{Float64})
  from tally(x::Array) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2
Arguments
  #self#::Core.Const(Main.tally)
  x::Vector{Float64}
Locals
  @_3::Union{Nothing, Tuple{Float64, Int64}}
  s::Float64
  v::Float64
Body::Float64
1 ─ %1  = Main.zero::Core.Const(zero)
│   %2  = Main.eltype::Core.Const(eltype)
│   %3  = (%2)(x)::Core.Const(Float64)
│         (s = (%1)(%3))
│   %5  = x::Vector{Float64}
│         (@_3 = Base.iterate(%5))
│   %7  = @_3::Union{Nothing, Tuple{Float64, Int64}}
│   %8  = (%7 === nothing)::Bool
│   %9  = Base.not_int(%8)::Bool
└──       goto #4 if not %9
2 ┄ %11 = @_3::Tuple{Float64, Int64}
│         (v = Core.getfield(%11, 1))
│   %13 = Core.getfield(%11, 2)::Int64
│   %14 = Main.:+::Core.Const(+)
│   %15 = s::Float64
│   %16 = v::Float64
│         (s = (%14)(%15, %16))
│         (@_3 = Base.iterate(%5, %13))
│   %19 = @_3

In [260]:
# check LLVM bitcode
@code_llvm tally(a)

; Function Signature: tally(Array{Float64, 1})
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2 within `tally`
define double @julia_tally_36385(ptr noundef nonnull align 8 dereferenceable(24) %"x::Array") #0 {
top:
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:4 within `tally`
; ┌ @ array.jl:901 within `iterate` @ array.jl:901
; │┌ @ essentials.jl:11 within `length`
    %"x::Array.size_ptr" = getelementptr inbounds i8, ptr %"x::Array", i64 16
    %"x::Array.size.0.copyload" = load i64, ptr %"x::Array.size_ptr", align 8
; │└
; │┌ @ int.jl:519 within `<`
    %.not.not = icmp eq i64 %"x::Array.size.0.copyload", 0
; │└
   br i1 %.not.not, label %L75, label %L34

L34:                                              ; preds = %top
; │┌ @ essentials.jl:920 within `getindex`
    

In [261]:
@code_native tally(a)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_tally_36389              ; -- Begin function julia_tally_36389
	.p2align	2
_julia_tally_36389:                     ; @julia_tally_36389
; Function Signature: tally(Array{Float64, 1})
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2 within `tally`
; %bb.0:                                ; %top
	;DEBUG_VALUE: tally:x <- [$x0+0]
	;DEBUG_VALUE: tally:x <- [$x0+0]
; │ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:4 within `tally`
; │┌ @ array.jl:901 within `iterate` @ array.jl:901
; ││┌ @ essentials.jl:11 within `length`
	ldr	x8, [x0, #16]
; ││└
	cbz	x8, LBB0_4
; %bb.1:                                ; %L34
; ││┌ @ essentials.jl:920 within `getindex`
	ldr	x9, [x0]
	ldr	d0, [x9]
	movi

**Exercise:** Annotate the loop in `tally` function by `@turbo` from the `LoopVectorization.jl` package and look for the difference in LLVM bitcode and machine code.

## Memory profiling

Detailed memory profiling requires a detour. First let's write a script `bar.jl`, which contains the workload function `tally` and a wrapper for profiling.

In [262]:
# run shell command
run(`cat bar.jl`)

using Profile

function tally(x::Array)
    s = zero(eltype(x))
    for v in x
        s += v
    end
    s
end

# call workload from wrapper to avoid misattribution bug
function wrapper()
    y = rand(10000)
    # force compilation
    println(tally(y))
    # clear allocation counters
    Profile.clear_malloc_data()
    # run compiled workload
    println(tally(y))
end

wrapper()


Process(`cat bar.jl`, ProcessExited(0))

Next, in terminal, we run the script with `--track-allocation=user` option.

In [263]:
#;julia --track-allocation=user bar.jl

The profiler outputs a file `bar.jl.51116.mem`.

In [264]:
run(`cat bar.jl.51116.mem`)

        - using Profile
        - 
        - function tally(x::Array)
        -     s = zero(eltype(x))
        -     for v in x
        -         s += v
        -     end
        -     s
        - end
        - 
        - # call workload from wrapper to avoid misattribution bug
        - function wrapper()
        0     y = rand(10000)
        -     # force compilation
        0     println(tally(y))
        -     # clear allocation counters
        0     Profile.clear_malloc_data()
        -     # run compiled workload
      528     println(tally(y))
        - end
        - 
        - wrapper()
        - 


Process(`cat bar.jl.51116.mem`, ProcessExited(0))