<img src="./julia_logo.png" align="center" width="400"/>

System information (for reproducibility)

In [12]:
versioninfo()

Julia Version 1.12.5
Commit 5fe89b8ddc1 (2026-02-09 16:05 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 8 default, 1 interactive, 8 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = code


Load packages:

In [13]:
using Pkg
Pkg.activate(pwd())
Pkg.instantiate()
Pkg.status()

  Activating project at `~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro`


Status `~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/Project.toml`
⌃ [6e4b80f9] BenchmarkTools v1.6.3
  [31c24e10] Distributions v0.25.123
  [6f49c342] RCall v0.14.12
  [37e2e46d] LinearAlgebra v1.12.0
  [9abbd945] Profile v1.11.0
  [2f01184e] SparseArrays v1.12.0
Info Packages marked with ⌃ have new versions available and may be upgradable.


In [14]:
using BenchmarkTools, Distributions, RCall
using LinearAlgebra, Profile, SparseArrays

## What's Julia?

> Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments

<img src="./julia_python_r_timeline.png" align="center" width="500"/>

* History:
  - Project started in 2009. First public release in 2012 
  - Creators: Jeff Bezanson, Alan Edelman, Stefan Karpinski, Viral Shah
  - First major release v1.0 was released on Aug 8, 2018
  - Current stable release v1.11.4 (as of Apr 1, 2025)

* Aim to solve the notorious **two language problem**: Prototype code goes into high-level languages like R/Python, production code goes into low-level language like C/C++. 

    Julia aims to:  
    
> Walks like Python. Runs like C.

<img src="./julia_vs_otherlang.png" align="center" width="600"/>

See <https://julialang.org/benchmarks/> for the details of benchmark.

* Write high-level, abstract code that closely resembles mathematical formulas
    - yet produces fast, low-level machine code that has traditionally only been generated by static languages.

* Julia is more than just "Fast R" or "Fast Matlab"
    - Performance comes from features that work well together.  
    - You can't just take the magic dust that makes Julia fast and sprinkle it on [language of choice]

## Learning resources

1. The (free) online course [Introduction to Julia](https://juliaacademy.com/p/intro-to-julia), by Jane Herriman. 

2. Cheat sheet: [The Fast Track to Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/).  

3. Browse the Julia [documentation](https://docs.julialang.org/en).  

4. For Matlab users, read [Noteworthy Differences From Matlab](https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Noteworthy-differences-from-MATLAB-1).  

    For R users, read [Noteworthy Differences From R](https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Noteworthy-differences-from-R-1).  

    For Python users, read [Noteworthy Differences From Python](https://docs.julialang.org/en/v1/manual/noteworthy-differences/?highlight=matlab#Noteworthy-differences-from-Python-1).  

5. The [Learning page](http://julialang.org/learning/) on Julia's website has pointers to many other learning resources.  

## Julia REPL (Read-Evaluation-Print-Loop)

The `Julia` REPL, or `Julia` shell, has at least five modes.

1. **Default mode** is the Julian prompt `julia>`. Type backspace in other modes to enter default mode.    

2. **Help mode** `help?>`. Type `?` to enter help mode. `?search_term` does a fuzzy search for `search_term`.  

3. **Shell mode** `shell>`. Type `;` to enter shell mode.  

4. **Package mode** `(@v1.12) pkg>`. Type `]` to enter package mode for managing Julia packages (install, uninstall, update, ...).

5. **Search mode** `(reverse-i-search)`. Press `ctrl+R` to enter search model. 

6. With `RCall.jl` package installed, we can enter the **R mode** by typing `$` (shift+4) at Julia REPL.

Some survival commands in Julia REPL:  

1. `exit()` or `Ctrl+D`: exit Julia.

2. `Ctrl+C`: interrupt execution.

3. `Ctrl+L`: clear screen.

0. Append `;` (semi-colon) to suppress displaying output from a command. Same as Matlab.

0. `include("filename.jl")` to source a Julia code file.

## Seek help

* Online help from REPL: `?function_name`.

* Google.

* Julia documentation: <https://docs.julialang.org/en/>.

* Look up source code: `@edit sin(π)`.

* Discourse: <https://discourse.julialang.org>.

* Friends.

## Which IDE?

* Many choices: Positron, VS Code, Vim, ...

* For dynamic document, e.g., homework, I recommend [JupyterLab](http://jupyterlab.readthedocs.io/en/stable/) or VS Code (with Jupyter extension) or Positron. 

* For extensive Julia coding, myself has been happily using [VS Code](https://code.visualstudio.com) with extensions `Julia` and `VS Code Jupyter Notebook Previewer` installed. 

## Julia package system

* Each Julia package is a Git repository. Each Julia package name ends with `.jl`. E.g., `Distributions.jl` package lives at <https://github.com/JuliaStats/Distributions.jl>.   
Google search with `PackageName.jl` usually leads to the package on github.com. 

* The package ecosystem is rapidly maturing; a complete list of **registered** packages (which are required to have a certain level of testing and documentation) is at [http://pkg.julialang.org/](http://pkg.julialang.org/).

* For example, the package called `Distributions.jl` is added with
```julia
# in Pkg mode
(@v1.12) pkg> add Distributions
```
and "removed" (although not completely deleted) with
```julia
# in Pkg mode
(@v1.12) pkg> rm Distributions
```
* The package manager provides a dependency solver that determines which packages are actually required to be installed.

* **Non-registered** packages are added by cloning the relevant Git repository. E.g.,
```julia
# in Pkg mode
(@v1.12) pkg> add https://github.com/OpenMendel/SnpArrays.jl
```

* A package needs only be added once, at which point it is downloaded into your local `.julia/packages` directory in your home directory. 

In [15]:
readdir(Sys.islinux() ? ENV["JULIA_PATH"] * "/pkg/packages" : ENV["HOME"] * "/.julia/packages")

869-element Vector{String}:
 "ADTypes"
 "AMD"
 "ANSIColoredPrinters"
 "ASL_jll"
 "AbstractAlgebra"
 "AbstractFFTs"
 "AbstractLattices"
 "AbstractTrees"
 "Accessors"
 "AccurateArithmetic"
 ⋮
 "libvorbis_jll"
 "libwebp_jll"
 "micromamba_jll"
 "mtdev_jll"
 "oneTBB_jll"
 "pixi_jll"
 "x264_jll"
 "x265_jll"
 "xkbcommon_jll"

* Directory of a specific package can be queried by `pathof()`:

In [16]:
pathof(Distributions)

"/Users/huazhou/.julia/packages/Distributions/xMnxM/src/Distributions.jl"

* If you start having problems with packages that seem to be unsolvable, you may try just deleting your .julia directory and reinstalling all your packages. 

* Periodically, one should run `update` in Pkg mode, which checks for, downloads and installs updated versions of all the packages you currently have installed.

* `status` lists the status of all installed packages.

* Using functions in package.
```julia
using Distributions
```
This pulls all of the *exported* functions in the module into your local namespace, as you can check using the `whos()` command. An alternative is
```julia
import Distributions
```
Now, the functions from the Distributions package are available only using 
```julia
Distributions.<FUNNAME>
```
All functions, not only exported functions, are always available like this.

## Calling R from Julia

* The [`RCall.jl`](https://github.com/JuliaInterop/RCall.jl) package allows us to embed R code inside of Julia.

* There are also `PyCall.jl`, `MATLAB.jl`, `JavaCall.jl`, `CxxWrap.jl` packages for interfacing with other languages.

In [17]:
# x is in Julia workspace
x = randn(1000)

# $ is the interpolation operator
R"""
hist($x, main = "I'm plotting a Julia vector")
""";

In [18]:
R"""
library(ggplot2)

qplot($x)
"""

RObject{S4Sxp}


┌ Warning: RCall.jl: `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
└ @ RCall /Users/huazhou/.julia/packages/RCall/FKyW5/src/io.jl:166


In [19]:
x = R"""
rnorm(10)
"""

RObject{RealSxp}
 [1]  1.3158505 -0.6015719 -0.5376756  1.4317283  0.2249369  0.8726821
 [7]  2.4210667 -2.2715066  1.0140247 -0.8070479


In [20]:
# collect R variable into Julia workspace
y = collect(x)

10-element Vector{Float64}:
  1.3158505058271017
 -0.6015718501614076
 -0.5376756216647878
  1.431728297823681
  0.2249368685613434
  0.8726821166814009
  2.421066708688757
 -2.271506581552274
  1.014024665615388
 -0.8070479176188832

* Access Julia variables in R REPL mode:
```julia
julia> x = rand(5) # Julia variable
R> y <- $x
```

* Pass Julia expression in R REPL mode:
```julia
R> y <- $(rand(5))
```

* Put Julia variable into R environment:
```julia
julia> @rput x
R> x
```

* Get R variable into Julia environment:
```julia
R> r <- 2
Julia> @rget r
```

* If you want to call Julia within R, check out the [`JuliaCall`](https://non-contradiction.github.io/JuliaCall//index.html) package.

## Some basic Julia code

In [21]:
# an integer, same as int in R
y = 1

1

In [22]:
# query type of a Julia object
typeof(y)

Int64

In [23]:
# a Float64 number, same as double in R
y = 1.0

1.0

In [24]:
typeof(y) 

Float64

In [25]:
# Greek letters:  `\pi<tab>`
π

π = 3.1415926535897...

In [26]:
typeof(π)

Irrational{:π}

In [27]:
# Greek letters:  `\theta<tab>`
θ = y + π

4.141592653589793

In [28]:
# emoji! `\:kissing_cat:<tab>`
😽 = 5.0
😽 + 1

6.0

In [29]:
# `\alpha<tab>\hat<tab>`
α̂ = π

π = 3.1415926535897...

For a list of unicode symbols that can be tab-completed, see <https://docs.julialang.org/en/v1/manual/unicode-input/>. Or in the help mode, type `?` followed by the unicode symbol you want to input.

In [30]:
# vector of Float64 0s
x = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [31]:
# vector Int64 0s
x = zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [32]:
# matrix of Float64 0s
x = zeros(5, 3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [33]:
# matrix of Float64 1s
x = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [34]:
# define array without initialization
x = Matrix{Float64}(undef, 5, 3)

5×3 Matrix{Float64}:
 1.91693e-319  4.0e-323  4.94e-322
 2.68136e-314  1.6e-322  4.94e-321
 2.68136e-314  1.5e-323  1.235e-321
 1.5e-323      5.0e-324  1.6e-322
 2.0e-323      5.0e-324  2.37896e-314

In [35]:
# fill a matrix by 0s
fill!(x, 0)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [36]:
# initialize an array to be constant 2.5
fill(2.5, (5, 3))

5×3 Matrix{Float64}:
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5

In [37]:
# rational number
a = 3//5

3//5

In [38]:
typeof(a)

Rational{Int64}

In [39]:
b = 3//7

3//7

In [40]:
a + b

36//35

In [41]:
# uniform [0, 1) random numbers
x = rand(5, 3)

5×3 Matrix{Float64}:
 0.156992   0.241608  0.579232
 0.0946666  0.491025  0.768085
 0.116164   0.247493  0.688799
 0.439531   0.393794  0.867399
 0.881762   0.612193  0.956562

In [42]:
# uniform random numbers (in single precision)
x = rand(Float16, 5, 3)

5×3 Matrix{Float16}:
 0.724   0.1875  0.3965
 0.1426  0.9707  0.9004
 0.2861  0.1323  0.9463
 0.632   0.1436  0.5684
 0.1353  0.7075  0.861

In [43]:
# random numbers from {1,...,5}
x = rand(1:5, 5, 3)

5×3 Matrix{Int64}:
 2  5  2
 2  2  3
 3  1  3
 4  4  5
 2  5  1

In [44]:
# standard normal random numbers
x = randn(5, 3)

5×3 Matrix{Float64}:
 -0.062658   1.09043   -0.619982
 -0.277097  -0.931512   0.307238
 -0.233648  -0.233912   1.58342
  0.129661  -2.13643    0.936234
  0.271674  -1.0589    -0.424673

In [45]:
# range
1:10

1:10

In [46]:
typeof(1:10)

UnitRange{Int64}

In [47]:
1:2:10

1:2:9

In [48]:
typeof(1:2:10)

StepRange{Int64, Int64}

In [49]:
# integers 1-10
x = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [50]:
# or equivalently
[1:10...]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [51]:
# Float64 numbers 1-10
x = collect(1.0:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [52]:
# convert to a specific type
convert(Vector{Float64}, 1:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [53]:
# syntactically same as above
Float64.(1:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

## Matrices and vectors

### Dimensions

In [54]:
x = randn(5, 3)

5×3 Matrix{Float64}:
  0.409915  -0.801324   1.41166
  1.08532    0.385077   0.376087
  0.093815  -1.94777   -0.0699554
 -0.322406  -0.609529  -0.0220249
  2.66147    0.251724   0.994948

In [55]:
size(x)

(5, 3)

In [56]:
size(x, 1) # nrow() in R

5

In [57]:
size(x, 2) # ncol() in R

3

In [58]:
# total number of elements
length(x)

15

### Indexing

In [59]:
# 5 × 5 matrix of random Normal(0, 1)
x = randn(5, 5)

5×5 Matrix{Float64}:
 -0.389391  -0.110814   0.278776   1.01849    0.419244
  0.483211  -0.237478  -1.69503   -1.5384     1.01176
  1.23511    1.37982    1.08854   -1.07282   -0.37093
 -0.609827  -0.455804   1.92794    0.951961   0.892721
 -0.296002   0.282135   0.994082   1.67263   -0.221868

In [60]:
# first column
x[:, 1]

5-element Vector{Float64}:
 -0.38939139543909784
  0.4832114146188885
  1.235110068613278
 -0.6098272987089263
 -0.2960024032620648

In [61]:
# first row
x[1, :]

5-element Vector{Float64}:
 -0.38939139543909784
 -0.1108137009972483
  0.2787762492336953
  1.0184924138168385
  0.4192439480421778

In [62]:
# sub-array
x[1:2, 2:3]

2×2 Matrix{Float64}:
 -0.110814   0.278776
 -0.237478  -1.69503

In [63]:
# getting a subset of a matrix creates a copy, but you can also create "views"
z = view(x, 1:2, 2:3)

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 -0.110814   0.278776
 -0.237478  -1.69503

In [64]:
# same as
@views z = x[1:2, 2:3]

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 -0.110814   0.278776
 -0.237478  -1.69503

In [65]:
# change in z (view) changes x as well
z[2, 2] = 0.0
x

5×5 Matrix{Float64}:
 -0.389391  -0.110814  0.278776   1.01849    0.419244
  0.483211  -0.237478  0.0       -1.5384     1.01176
  1.23511    1.37982   1.08854   -1.07282   -0.37093
 -0.609827  -0.455804  1.92794    0.951961   0.892721
 -0.296002   0.282135  0.994082   1.67263   -0.221868

In [66]:
# y points to same data as x
y = x

5×5 Matrix{Float64}:
 -0.389391  -0.110814  0.278776   1.01849    0.419244
  0.483211  -0.237478  0.0       -1.5384     1.01176
  1.23511    1.37982   1.08854   -1.07282   -0.37093
 -0.609827  -0.455804  1.92794    0.951961   0.892721
 -0.296002   0.282135  0.994082   1.67263   -0.221868

In [67]:
# x and y point to same data
pointer(x), pointer(y)

(Ptr{Float64}(0x0000000112480d40), Ptr{Float64}(0x0000000112480d40))

In [68]:
# changing y also changes x
y[:, 1] .= 0
x

5×5 Matrix{Float64}:
 0.0  -0.110814  0.278776   1.01849    0.419244
 0.0  -0.237478  0.0       -1.5384     1.01176
 0.0   1.37982   1.08854   -1.07282   -0.37093
 0.0  -0.455804  1.92794    0.951961   0.892721
 0.0   0.282135  0.994082   1.67263   -0.221868

In [69]:
# create a new copy of data
z = copy(x)

5×5 Matrix{Float64}:
 0.0  -0.110814  0.278776   1.01849    0.419244
 0.0  -0.237478  0.0       -1.5384     1.01176
 0.0   1.37982   1.08854   -1.07282   -0.37093
 0.0  -0.455804  1.92794    0.951961   0.892721
 0.0   0.282135  0.994082   1.67263   -0.221868

In [70]:
pointer(x), pointer(z)

(Ptr{Float64}(0x0000000112480d40), Ptr{Float64}(0x0000000144e443a0))

### Concatenate matrices

In [71]:
# 3-by-1 vector
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [72]:
# 1-by-3 array
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [73]:
# multiple assignment by tuple
x, y, z = randn(5, 3), randn(5, 2), randn(3, 5)

([1.481274390704599 -0.8728077451577957 -0.5767560748569945; -1.5381586108549663 -1.1605104319086064 -0.4839020309184712; … ; 0.40713143204107827 -0.07521892986501053 -0.5662566812832384; 1.5680783421841673 -0.3159401942314073 0.031244542499555234], [0.3167787720671227 -1.8949796484969064; -0.0864394495662824 -0.7318812185517373; … ; -1.3673947164128482 0.9390702477030621; 1.6691965860182567 -0.747092273323902], [0.701470463488005 -1.2279455802040267 … 0.3449387354423206 0.3644412189256487; 0.44264633526849717 0.2610873384151554 … -1.3086026378972213 -0.28750941454253737; 0.6861136528348865 -0.7465798716040307 … 0.5918844423413819 -0.3865213536713561])

In [74]:
[x y] # 5-by-5 matrix

5×5 Matrix{Float64}:
  1.48127   -0.872808   -0.576756    0.316779   -1.89498
 -1.53816   -1.16051    -0.483902   -0.0864394  -0.731881
 -1.40715   -0.0560699   0.541961    0.514828    1.02271
  0.407131  -0.0752189  -0.566257   -1.36739     0.93907
  1.56808   -0.31594     0.0312445   1.6692     -0.747092

In [75]:
[x y; z] # 8-by-5 matrix

8×5 Matrix{Float64}:
  1.48127   -0.872808   -0.576756    0.316779   -1.89498
 -1.53816   -1.16051    -0.483902   -0.0864394  -0.731881
 -1.40715   -0.0560699   0.541961    0.514828    1.02271
  0.407131  -0.0752189  -0.566257   -1.36739     0.93907
  1.56808   -0.31594     0.0312445   1.6692     -0.747092
  0.70147   -1.22795     0.545783    0.344939    0.364441
  0.442646   0.261087    0.83963    -1.3086     -0.287509
  0.686114  -0.74658     0.401878    0.591884   -0.386521

### Dot operation (broadcasting)

Dot operation in Julia is elementwise operation, similar to Matlab.

In [76]:
x = randn(5, 3)

5×3 Matrix{Float64}:
  0.683527    1.55743    0.767051
  1.14928     0.234501   0.829697
  1.37374    -1.4244    -0.357243
 -0.0514637  -0.612177  -0.674175
  0.692436    0.340407   0.34535

In [77]:
y = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [78]:
x .* y # same x * y in R

5×3 Matrix{Float64}:
  0.683527    1.55743    0.767051
  1.14928     0.234501   0.829697
  1.37374    -1.4244    -0.357243
 -0.0514637  -0.612177  -0.674175
  0.692436    0.340407   0.34535

In [79]:
x .^ (-2)

5×3 Matrix{Float64}:
   2.14037    0.412272  1.69962
   0.757087  18.1849    1.45265
   0.529899   0.492873  7.83562
 377.571      2.66837   2.20016
   2.08565    8.62985   8.38458

In [80]:
sin.(x)

5×3 Matrix{Float64}:
  0.631532   0.999911   0.694015
  0.912471   0.232358   0.737727
  0.980646  -0.989303  -0.349692
 -0.051441  -0.57465   -0.624253
  0.638414   0.333871   0.338526

### Basic linear algebra

In [81]:
x = randn(5)

5-element Vector{Float64}:
  0.13595950168156698
  0.7489835685494067
 -0.005097969664776884
  0.6877195147586462
 -0.6931484377401067

In [82]:
# vector L2 norm
norm(x)

1.2381034888371105

In [83]:
# same as
sqrt(sum(abs2, x))

1.2381034888371105

In [84]:
y = randn(5) # another vector
# dot product
dot(x, y) # x' * y

0.2638185684489711

In [85]:
# same as
x'y

0.2638185684489711

In [86]:
x, y = randn(5, 3), randn(3, 2)
# matrix multiplication, same as %*% in R
x * y

5×2 Matrix{Float64}:
 -0.86374    2.25659
 -2.72778    1.25883
 -2.49983   -1.06668
 -0.754669   2.46584
  0.522874  -2.10872

In [87]:
x = randn(3, 3)

3×3 Matrix{Float64}:
 1.78059   -1.51429   2.06589
 0.140736   1.39975   0.180924
 0.524466   1.05394  -0.226338

In [88]:
# conjugate transpose
x'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
  1.78059  0.140736   0.524466
 -1.51429  1.39975    1.05394
  2.06589  0.180924  -0.226338

In [89]:
b = rand(3)
x'b # same as x' * b

3-element Vector{Float64}:
 1.1183968560240436
 0.13016486565387192
 0.8224831988880333

In [90]:
# trace
tr(x)

2.953997690822187

In [91]:
det(x)

-2.3057557955545014

In [92]:
rank(x)

3

### Sparse matrices

In [93]:
# 10-by-10 sparse matrix with sparsity 0.1
X = sprandn(10, 10, .1)

10×10 SparseMatrixCSC{Float64, Int64} with 10 stored entries:
  ⋅     ⋅         ⋅        ⋅    ⋅   …   0.629063    ⋅          ⋅ 
  ⋅   -0.689093   ⋅        ⋅    ⋅        ⋅         1.29474     ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅        -0.859449    ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅   …    ⋅          ⋅        -0.576395
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅    0.627365   ⋅        ⋅    ⋅      -0.136879    ⋅          ⋅ 
  ⋅     ⋅        1.28572   ⋅    ⋅        ⋅          ⋅        -1.05459
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 

In [94]:
# dump() in Julia is like str() in R
dump(X)

SparseMatrixCSC{Float64, Int64}
  m: Int64 10
  n: Int64 10
  colptr: Array{Int64}((11,)) [1, 1, 3, 4, 4, 4, 5, 5, 7, 9, 11]
  rowval: Array{Int64}((10,)) [2, 8, 9, 5, 1, 8, 2, 3, 6, 9]
  nzval: Array{Float64}((10,)) [-0.6890928018663016, 0.6273654551462879, 1.2857180969685882, 0.22596759600950114, 0.6290630165545518, -0.1368793676175301, 1.294738534438998, -0.859448599134883, -0.5763946174311372, -1.0545877747558767]


In [95]:
# convert to dense matrix; be cautious when dealing with big data
Xfull = convert(Matrix{Float64}, X)

10×10 Matrix{Float64}:
 0.0   0.0       0.0      0.0  0.0  …   0.629063   0.0        0.0
 0.0  -0.689093  0.0      0.0  0.0      0.0        1.29474    0.0
 0.0   0.0       0.0      0.0  0.0      0.0       -0.859449   0.0
 0.0   0.0       0.0      0.0  0.0      0.0        0.0        0.0
 0.0   0.0       0.0      0.0  0.0      0.0        0.0        0.0
 0.0   0.0       0.0      0.0  0.0  …   0.0        0.0       -0.576395
 0.0   0.0       0.0      0.0  0.0      0.0        0.0        0.0
 0.0   0.627365  0.0      0.0  0.0     -0.136879   0.0        0.0
 0.0   0.0       1.28572  0.0  0.0      0.0        0.0       -1.05459
 0.0   0.0       0.0      0.0  0.0      0.0        0.0        0.0

In [96]:
# convert a dense matrix to sparse matrix
sparse(Xfull)

10×10 SparseMatrixCSC{Float64, Int64} with 10 stored entries:
  ⋅     ⋅         ⋅        ⋅    ⋅   …   0.629063    ⋅          ⋅ 
  ⋅   -0.689093   ⋅        ⋅    ⋅        ⋅         1.29474     ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅        -0.859449    ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅     ⋅         ⋅        ⋅    ⋅   …    ⋅          ⋅        -0.576395
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 
  ⋅    0.627365   ⋅        ⋅    ⋅      -0.136879    ⋅          ⋅ 
  ⋅     ⋅        1.28572   ⋅    ⋅        ⋅          ⋅        -1.05459
  ⋅     ⋅         ⋅        ⋅    ⋅        ⋅          ⋅          ⋅ 

In [97]:
# syntax for sparse linear algebra is same as dense linear algebra
β = ones(10)
X * β

10-element Vector{Float64}:
  0.6290630165545518
  0.6056457325726963
 -0.859448599134883
  0.0
  0.22596759600950114
 -0.5763946174311372
  0.0
  0.49048608752875783
  0.23113032221271146
  0.0

In [98]:
# many functions apply to sparse matrices as well
sum(X)

0.7464495383121981

## Control flow and loops

* if-elseif-else-end

```julia
if condition1
    # do something
elseif condition2
    # do something
else
    # do something
end
```

* `for` loop

```julia
for i in 1:10
    println(i)
end
```

* Nested `for` loop:

```julia
for i in 1:10
    for j in 1:5
        println(i * j)
    end
end
```
Same as

```julia
for i in 1:10, j in 1:5
    println(i * j)
end
```

* Exit loop:

```julia
for i in 1:10
    # do something
    if condition1
        break # skip remaining loop
    end
end
```

* Exit iteration:  

```julia
for i in 1:10
    # do something
    if condition1
        continue # skip to next iteration
    end
    # do something
end
```

## Functions 

* In Julia, all arguments to functions are **passed by reference**, in contrast to R and Matlab.

* Function names ending with `!` indicates that function mutates at least one argument, typically the first.
```julia
sort!(x) # vs sort(x)
```

* Function definition

```julia
function func(req1, req2; key1=dflt1, key2=dflt2)
    # do stuff
    return out1, out2, out3
end
```
**Required arguments** are separated with a comma and use the positional notation.  
**Optional arguments** need a default value in the signature.  
**Semicolon** is not required in function call.  
**return** statement is optional.  
Multiple outputs can be returned as a **tuple**, e.g., `return out1, out2, out3`.  

* Anonymous functions, e.g., `x -> x^2`, is commonly used in collection function or list comprehensions.
```julia
map(x -> x^2, y) # square each element in x
```

* Functions can be nested:

```julia
function outerfunction()
    # do some outer stuff
    function innerfunction()
        # do inner stuff
        # can access prior outer definitions
    end
    # do more outer stuff
end
```

* Scalar functions can be vectorized using the Dot syntax:

In [99]:
# defined for scalar
function myfunc(x)
    return sin(x^2)
end

x = randn(5, 3)
myfunc.(x)

5×3 Matrix{Float64}:
 0.0195275   0.923072   0.0335038
 0.00655637  0.756865   0.129147
 0.587496    0.523862  -0.363651
 0.978765    0.186662   0.888756
 0.0255293   0.200164   0.339054

* **Collection function** (think this as the series of `apply` functions in R).

    Apply a function to each element of a collection:

```julia
map(f, coll) # or
map(coll) do elem
    # do stuff with elem
    # must contain return
end
```

In [100]:
map(x -> sin(x^2), x)

5×3 Matrix{Float64}:
 0.0195275   0.923072   0.0335038
 0.00655637  0.756865   0.129147
 0.587496    0.523862  -0.363651
 0.978765    0.186662   0.888756
 0.0255293   0.200164   0.339054

In [101]:
map(x) do elem
    elem = elem^2
    return sin(elem)
end

5×3 Matrix{Float64}:
 0.0195275   0.923072   0.0335038
 0.00655637  0.756865   0.129147
 0.587496    0.523862  -0.363651
 0.978765    0.186662   0.888756
 0.0255293   0.200164   0.339054

In [102]:
# Mapreduce
mapreduce(x -> sin(x^2), +, x)

5.235308687839241

In [103]:
# same as
sum(x -> sin(x^2), x)

5.235308687839241

* List **comprehension**

In [104]:
[sin(2i + j) for i in 1:5, j in 1:3] # similar to Python

5×3 Matrix{Float64}:
  0.14112   -0.756802  -0.958924
 -0.958924  -0.279415   0.656987
  0.656987   0.989358   0.412118
  0.412118  -0.544021  -0.99999
 -0.99999   -0.536573   0.420167

## Type system

* Every variable in Julia has a type.

* When thinking about types, think about sets.

* Everything is a subtype of the abstract type `Any`.

* An abstract type defines a set of types
    - Consider types in Julia that are a `Number`:

<img src="tree.png" width="800" align="center"/>

* We can explore type hierarchy with `typeof()`, `supertype()`, and `subtypes()`.

In [105]:
# 1.0: double precision, 1: 64-bit integer
typeof(1.0), typeof(1)

(Float64, Int64)

In [106]:
supertype(Float64)

AbstractFloat

In [107]:
subtypes(AbstractFloat)

5-element Vector{Any}:
 BigFloat
 Core.BFloat16
 Float16
 Float32
 Float64

In [108]:
# Is Float64 a subtype of AbstractFloat?
Float64 <: AbstractFloat

true

In [109]:
# On 64bit machine, Int == Int64
Int == Int64

true

In [110]:
# convert to Float64
convert(Float64, 1)

1.0

In [111]:
# same as casting
Float64(1)

1.0

In [112]:
# Float32 vector
x = randn(Float32, 5)

5-element Vector{Float32}:
 -0.07436206
  0.23512053
  0.3585976
 -0.8691367
 -0.56122345

In [113]:
# convert to Float64
convert(Vector{Float64}, x)

5-element Vector{Float64}:
 -0.07436206191778183
  0.23512053489685059
  0.35859760642051697
 -0.8691366910934448
 -0.5612234473228455

In [114]:
# same as broadcasting (dot operatation)
Float64.(x)

5-element Vector{Float64}:
 -0.07436206191778183
  0.23512053489685059
  0.35859760642051697
 -0.8691366910934448
 -0.5612234473228455

In [115]:
# convert Float64 to Int64
convert(Int, 1.0)

1

In [116]:
convert(Int, 1.5) # should use round(1.5)

InexactError: InexactError: Int64(1.5)

In [117]:
round(Int, 1.5)

2

## Multiple dispatch

* Multiple dispatch lies in the core of Julia design. It allows built-in and user-defined functions to be overloaded for different combinations of argument types.

* Let's consider a simple "doubling" function:

In [118]:
g(x) = x + x

g (generic function with 1 method)

In [119]:
g(1.5)

3.0

This definition is too broad, since some things, e.g., strings, can't be added 

In [120]:
g("hello world")

MethodError: MethodError: no method matching +(::String, ::String)
The function `+` exists, but no method is defined for this combination of argument types.
String concatenation is performed with * (See also: https://docs.julialang.org/en/v1/manual/strings/#man-concatenation).

Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:642
  +(!Matched::Pkg.Resolve.FieldValue, !Matched::Pkg.Resolve.FieldValue)
   @ Pkg ~/.julia/juliaup/julia-1.12.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Pkg/src/Resolve/fieldvalues.jl:45
  +(!Matched::Bool, !Matched::Complex{Bool})
   @ Base complex.jl:308
  ...


* This definition is correct but too restrictive, since any `Number` can be added.

In [121]:
g(x::Float64) = x + x

g (generic function with 2 methods)

* This definition will automatically work on the entire type tree above!

In [122]:
g(x::Number) = x + x

g (generic function with 3 methods)

This is a lot nicer than 
```julia
function g(x)
    if isa(x, Number)
        return x + x
    else
        throw(ArgumentError("x should be a number"))
    end
end
```

* `methods(func)` function display all methods defined for `func`.

In [123]:
methods(g)

# 3 methods for generic function "g" from Main:
 [1] g(x::Float64)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1
 [2] g(x::Number)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1
 [3] g(x)
     @ ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y236sZmlsZQ==.jl:1

* When calling a function with multiple definitions, Julia will search from the narrowest signature to the broadest signature.

* `@which func(x)` marco tells which method is being used for argument signature `x`.

In [124]:
# an Int64 input
@which g(1)

g(x::Number)
     @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1

In [125]:
# a Vector{Float64} input
@which g(randn(5))

g(x)
     @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y236sZmlsZQ==.jl:1

## Just-in-time compilation (JIT)

Following figures are taken from Arch D. Robinson's slides [Introduction to Writing High Performance Julia](https://www.youtube.com/watch?v=szE4txAD8mk).


| <img src="./julia_toolchain.png" alt="Julia toolchain" style="width: 400px;"/> | <img src="./julia_introspect.png" alt="Julia toolchain" style="width: 500px;"/> |
|----------------------------------|------------------------------------|
|||

* `Julia`'s efficiency results from its capability to infer the types of **all** variables within a function and then call LLVM compiler to generate optimized machine code at run-time. 

Consider the `g` (doubling) function defined earlier. This function will work on **any** type which has a method for `+`.

In [126]:
g(2), g(2.0)

(4, 4.0)

**Step 1**: Parse Julia code into [abstract syntax tree (AST)](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

In [127]:
@code_lowered g(2)

CodeInfo(
1 ─ %1 = Main.:+
│   %2 =   dynamic (%1)(x, x)
└──      return %2
)

**Step 2**: Type inference according to input type.

In [128]:
# type inference for integer input
@code_warntype g(2)

MethodInstance for g(::Int64)
  from g(x::Number) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1
Arguments
  #self#::Core.Const(Main.g)
  x::Int64
Body::Int64
1 ─ %1 = Main.:+::Core.Const(+)
│   %2 = (%1)(x, x)::Int64
└──      return %2



In [129]:
# type inference for Float64 input
@code_warntype g(2.0)

MethodInstance for g(::Float64)
  from g(x::Float64) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1
Arguments
  #self#::Core.Const(Main.g)
  x::Float64
Body::Float64
1 ─ %1 = Main.:+::Core.Const(+)
│   %2 = (%1)(x, x)::Float64
└──      return %2



**Step 3**: Compile into **LLVM bitcode** (equivalent of R bytecode generated by the `compiler` package).

In [130]:
# LLVM bitcode for integer input
@code_llvm g(2)

; Function Signature: g(Int64)
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1 within `g`
define i64 @julia_g_31337(i64 signext %"x::Int64") #0 {
top:
; ┌ @ int.jl:87 within `+`
   %0 = shl i64 %"x::Int64", 1
   ret i64 %0
; └
}


In [131]:
# LLVM bitcode for Float64 input
@code_llvm g(2.0)

; Function Signature: g(Float64)
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1 within `g`
define double @julia_g_31395(double %"x::Float64") #0 {
top:
; ┌ @ float.jl:495 within `+`
   %0 = fadd double %"x::Float64", %"x::Float64"
   ret double %0
; └
}


We didn't provide a type annotation. But different LLVM bitcodes were generated depending on the argument type!

In R or Python, `g(2)` and `g(2.0)` would use the same code for both.

In Julia, `g(2)` and `g(2.0)` dispatches to optimized code for `Int64` and `Float64`, respectively.

For integer input `x`, LLVM compiler is smart enough to know `x + x` is simply shifting `x` by 1 bit, which is faster than addition.
 
* **Step 4**: Lowest level is the **assembly code**, which is machine dependent.

In [132]:
# Assembly code for integer input
@code_native g(2)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_g_31449                  ; -- Begin function julia_g_31449
	.p2align	2
_julia_g_31449:                         ; @julia_g_31449
; Function Signature: g(Int64)
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y246sZmlsZQ==.jl:1 within `g`
; %bb.0:                                ; %top
	;DEBUG_VALUE: g:x <- $x0
	;DEBUG_VALUE: g:x <- $x0
; │┌ @ int.jl:87 within `+`
	lsl	x0, x0, #1
	ret
; └└
                                        ; -- End function
.subsections_via_symbols


In [133]:
# Assembly code for Float64 input
@code_native g(2.0)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_g_31556                  ; -- Begin function julia_g_31556
	.p2align	2
_julia_g_31556:                         ; @julia_g_31556
; Function Signature: g(Float64)
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y244sZmlsZQ==.jl:1 within `g`
; %bb.0:                                ; %top
	;DEBUG_VALUE: g:x <- $d0
	;DEBUG_VALUE: g:x <- $d0
; │┌ @ float.jl:495 within `+`
	fadd	d0, d0, d0
	ret
; └└
                                        ; -- End function
	.section	__DATA,__const
	.p2align	3, 0x0                          ; @"+Core.Float64#31558"
"l_+Core.Float64#31558":
	.quad	"l_+Core.Float64#31558.jit"

.set "l_+Core.Float64#31558.jit", 4903129856
.subsections_via_symbols


## Profiling Julia code

Julia has several built-in tools for profiling. The `@time` marco outputs run time and heap allocation. Note the first call of a function incurs (substantial) compilation time.

In [134]:
# a function defined earlier
function tally(x::Array)
    s = zero(eltype(x))
    for v in x
        s += v
    end
    s
end

using Random
Random.seed!(257)
a = rand(20_000_000)
@time tally(a) # first run: include compile time

  0.022151 seconds (4.72 k allocations: 217.750 KiB, 18.32% compilation time)


1.000097950627383e7

In [135]:
@time tally(a)

  0.016468 seconds (1 allocation: 16 bytes)


1.000097950627383e7

For more robust benchmarking, the [BenchmarkTools.jl](https://github.com/JuliaCI/BenchmarkTools.jl) package is highly recommended.

In [136]:
@benchmark tally($a)

BenchmarkTools.Trial: 303 samples with 1 evaluation per sample.
 Range (min … max):  16.258 ms …  19.129 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.444 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   16.508 ms ± 345.195 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▁▁▅▂▇▆                                                       
  ███████▇▃▃▃▄▃▃▃▂▂▂▃▂▂▁▁▂▁▁▁▂▁▁▁▂▁▁▃▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂ ▃
  16.3 ms         Histogram: frequency by time         18.7 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.

The `Profile` module gives line by line profile results.

In [137]:
Profile.clear()
@profile tally(a)
Profile.print(format=:flat)

 Count  Overhead File                    Line Function
 =====  ======== ====                    ==== ========
     1         0 @Compiler/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/Compiler/src/abstractinterpretation.jl:4508\…ractinterpretation.jl]8;;\ 4508 typeinf(interp::Compiler.NativeIn…
     1         0 @Compiler/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/Compiler/src/optimize.jl:528\src/optimize.jl]8;;\  528 finish(interp::Compiler.NativeInt…
     1         0 @Compiler/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/Compiler/src/optimize.jl:1452\src/optimize.jl]8;;\ 1452 inline_cost
     1         0 @Compiler/]8;;vscode://file//Users/huazhou/.julia/juliaup/julia-1.12.5%2B0.aarch64.apple.darwin14/share/julia/Compiler/src/optimize.jl:1004\src/optimize.jl]8;;\ 1004 optimize(interp::Compiler.NativeI…
     

One can use [`ProfileView`](https://github.com/timholy/ProfileView.jl) package for better visualization of profile data:

```julia
using ProfileView

ProfileView.view()
```

In [138]:
# check type stability
@code_warntype tally(a)

MethodInstance for tally(::Vector{Float64})
  from tally(x::Array) @ Main ~/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2
Arguments
  #self#::Core.Const(Main.tally)
  x::Vector{Float64}
Locals
  @_3::Union{Nothing, Tuple{Float64, Int64}}
  s::Float64
  v::Float64
Body::Float64
1 ─ %1  = Main.zero::Core.Const(zero)
│   %2  = Main.eltype::Core.Const(eltype)
│   %3  = (%2)(x)::Core.Const(Float64)
│         (s = (%1)(%3))
│   %5  = x::Vector{Float64}
│         (@_3 = Base.iterate(%5))
│   %7  = @_3::Union{Nothing, Tuple{Float64, Int64}}
│   %8  = (%7 === nothing)::Bool
│   %9  = Base.not_int(%8)::Bool
└──       goto #4 if not %9
2 ┄ %11 = @_3::Tuple{Float64, Int64}
│         (v = Core.getfield(%11, 1))
│   %13 = Core.getfield(%11, 2)::Int64
│   %14 = Main.:+::Core.Const(+)
│   %15 = s::Float64
│   %16 = v::Float64
│         (s = (%14)(%15, %16))
│         (@_3 = Base.iterate(%5, %13))
│   %19 = @_3

In [139]:
# check LLVM bitcode
@code_llvm tally(a)

; Function Signature: tally(Array{Float64, 1})
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2 within `tally`
define double @julia_tally_35024(ptr noundef nonnull align 8 dereferenceable(24) %"x::Array") #0 {
top:
;  @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:4 within `tally`
; ┌ @ array.jl:901 within `iterate` @ array.jl:901
; │┌ @ essentials.jl:11 within `length`
    %"x::Array.size_ptr" = getelementptr inbounds i8, ptr %"x::Array", i64 16
    %"x::Array.size.0.copyload" = load i64, ptr %"x::Array.size_ptr", align 8
; │└
; │┌ @ int.jl:519 within `<`
    %.not.not = icmp eq i64 %"x::Array.size.0.copyload", 0
; │└
   br i1 %.not.not, label %L75, label %L34

L34:                                              ; preds = %top
; │┌ @ essentials.jl:920 within `getindex`
    

In [140]:
@code_native tally(a)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 16, 0
	.globl	_julia_tally_35028              ; -- Begin function julia_tally_35028
	.p2align	2
_julia_tally_35028:                     ; @julia_tally_35028
; Function Signature: tally(Array{Float64, 1})
; ┌ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:2 within `tally`
; %bb.0:                                ; %top
	;DEBUG_VALUE: tally:x <- [$x0+0]
	;DEBUG_VALUE: tally:x <- [$x0+0]
; │ @ /Users/huazhou/Documents/github.com/ucla-biostat-257/2026spring/slides/03-juliaintro/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y305sZmlsZQ==.jl:4 within `tally`
; │┌ @ array.jl:901 within `iterate` @ array.jl:901
; ││┌ @ essentials.jl:11 within `length`
	ldr	x8, [x0, #16]
; ││└
	cbz	x8, LBB0_4
; %bb.1:                                ; %L34
; ││┌ @ essentials.jl:920 within `getindex`
	ldr	x9, [x0]
	ldr	d0, [x9]
	movi

**Exercise:** Annotate the loop in `tally` function by `@turbo` from the `LoopVectorization.jl` package and look for the difference in LLVM bitcode and machine code.

## Memory profiling

Detailed memory profiling requires a detour. First let's write a script `bar.jl`, which contains the workload function `tally` and a wrapper for profiling.

In [141]:
# run shell command
run(`cat bar.jl`)

using Profile

function tally(x::Array)
    s = zero(eltype(x))
    for v in x
        s += v
    end
    s
end

# call workload from wrapper to avoid misattribution bug
function wrapper()
    y = rand(10000)
    # force compilation
    println(tally(y))
    # clear allocation counters
    Profile.clear_malloc_data()
    # run compiled workload
    println(tally(y))
end

wrapper()


Process(`cat bar.jl`, ProcessExited(0))

Next, in terminal, we run the script with `--track-allocation=user` option.

In [142]:
#;julia --track-allocation=user bar.jl

The profiler outputs a file `bar.jl.51116.mem`.

In [143]:
run(`cat bar.jl.51116.mem`)

        - using Profile
        - 
        - function tally(x::Array)
        -     s = zero(eltype(x))
        -     for v in x
        -         s += v
        -     end
        -     s
        - end
        - 
        - # call workload from wrapper to avoid misattribution bug
        - function wrapper()
        0     y = rand(10000)
        -     # force compilation
        0     println(tally(y))
        -     # clear allocation counters
        0     Profile.clear_malloc_data()
        -     # run compiled workload
      528     println(tally(y))
        - end
        - 
        - wrapper()
        - 


Process(`cat bar.jl.51116.mem`, ProcessExited(0))